// 文案外置(中文优先;加英文时改这里)
export const t = {
  appName: "扬州 yangzhou",
  nav: {
    projects: "项目",
    capabilities: "我的能力",
    attributes: "词表",
    members: "成员",
  },
  login: {
    title: "登录",
    username: "用户名",
    password: "密码",
    submit: "登录",
    hint: "全新服务器将以首个账号自动初始化",
    failed: "登录失败",
  },
  projects: {
    title: "项目",
    createKey: "KEY(如 CHE)",
    createName: "名称",
    create: "创建项目",
    empty: "还没有项目,建一个",
    enter: "打开看板",
    signalNow: "可行性",
  },
  board: {
    addItem: "新建 item",
    dropHere: "拖到这里",
    moveFailed: "迁移失败",
    detail: "详情",
  },
  item: {
    title: "标题",
    description: "描述",
    status: "状态",
    type: "类型",
    requirements: "需求",
    addRequirement: "加一条需求",
    attribute: "属性",
    minLevel: "最低等级",
    none: "不分级(presence)",
    save: "保存",
    saved: "已保存",
    verdicts: "判定",
    signal: "聚合信号",
    back: "← 返回看板",
  },
  caps: {
    title: "我的能力",
    hint: "自评等级 1–4;「未评级」= 有但不算差距;改动立即生效,各项目可行性随之更新。",
    none: "无",
    unrated: "未评级",
    has: "有",
    level: (l: number) => `Lv${l}`,
    empty: "词表为空,先到「词表」页添加属性。",
    saved: "已保存",
    saveFailed: "保存失败",
    back: "回到项目",
  },
  members: {
    title: "成员管理",
    newName: "新成员显示名",
    add: "建虚拟成员",
    virtual: "虚拟",
    real: "登录账号",
    teams: "分组",
    teamName: "组名",
    addTeam: "建分组",
    deleteTeam: "删组",
  },
  attrs: {
    title: "词表",
    hint: "Workspace 级统一语言:chess 练的 React,bookkeeping 也认。label→skill 只是一行数据,已有等级休眠不删。",
    name: "属性名",
    kindSkill: "skill(分级)",
    kindLabel: "label(不分级)",
    leveled: "分级",
    add: "添加",
    toKind: (target: string) => `→${target}`,
    unleveled: "取消分级",
    delete: "删除",
    createFailed: "创建失败",
    updateFailed: "更新失败",
    deleteFailed: "删除失败",
  },
  shortfall: {
    title: "短板面板",
    hint: "跨项目聚合缺口——我该练什么。",
    empty: "暂无缺口 ✔",
    missing: (n: number) => `缺门 ${n}`,
    delta: (n: number) => `共差 ${n} 级`,
    unrated: (n: number) => `未评级 ${n}`,
  },
  verdicts: {
    satisfied: (a: string) => `✓ 满足(${a})`,
    surplus: (a: string) => `✓ 有余(${a})`,
    gap: (a: string, d: number, r: number, act: number) => `△ 差 ${d} 级(${a}:需≥${r},有 ${act})`,
    unrated: (a: string, r: number) => `△ 有但未评级(${a},需≥${r})——差距未知`,
    missing: (a: string) => `✗ 缺能力(${a})`,
  },
  signal: {
    GREEN: "✔ 全满足",
    YELLOW: "△ 有差距",
    RED: "✗ 有缺门",
  },
};
