// 文案外置(中文优先;加英文时改这里)
export const t = {
  appName: "扬州 yangzhou",
  nav: {
    projects: "项目",
    capabilities: "我的能力",
    attributes: "词表",
    members: "成员",
  },
  login: {
    title: "登录",
    username: "用户名",
    password: "密码",
    submit: "登录",
    hint: "全新服务器将以首个账号自动初始化",
    failed: "登录失败",
  },
  projects: {
    title: "项目",
    createKey: "KEY(如 CHE)",
    createName: "名称",
    create: "创建项目",
    empty: "还没有项目,建一个",
    enter: "打开看板",
    signalNow: "可行性",
  },
  board: {
    addItem: "新建 item",
    dropHere: "拖到这里",
    moveFailed: "迁移失败",
    detail: "详情",
  },
  item: {
    title: "标题",
    description: "描述",
    status: "状态",
    type: "类型",
    requirements: "需求",
    addRequirement: "加一条需求",
    attribute: "属性",
    minLevel: "最低等级",
    none: "不分级(presence)",
    save: "保存",
    saved: "已保存",
    verdicts: "判定",
    signal: "聚合信号",
    back: "← 返回看板",
  },
  caps: {
    title: "我的能力",
    hint: "自评等级 1–4;「未评级」= 有但不算差距;改动立即生效,各项目可行性随之更新。",
    none: "无",
    unrated: "未评级",
    has: "有",
    level: (l: number) => `Lv${l}`,
    empty: "词表为空,先到「词表」页添加属性。",
    saved: "已保存",
    saveFailed: "保存失败",
    back: "回到项目",
  },
  members: {
    title: "成员管理",
    newName: "新成员显示名",
    add: "建虚拟成员",
    virtual: "虚拟",
    real: "登录账号",
    teams: "分组",
    teamName: "组名",
    addTeam: "建分组",
    deleteTeam: "删组",
  },
  wf: {
    button: "工作流",
    title: "工作流编辑",
    statuses: "状态列",
    addStatus: "添加列",
    newStatusName: "新状态名",
    transitions: "迁移表(空 = 自由迁移)",
    free: "(未配置——任意状态间自由迁移)",
    addTransition: "添加迁移",
    from: "从…",
    to: "到…",
    remove: "移除",
    start: "起点",
    final: "终态",
  },
  membersPanel: {
    button: "成员池",
    title: "项目成员池",
    poolConfigured: "已配置池:仅池内成员可被指派/进候选。",
    poolEmpty: "未配置池:全 workspace 成员可被指派。添加成员后,仅池内成员可被指派/进候选。",
    addable: "可添加的成员",
    allInPool: "(全员已在池中)",
    remove: "移除",
    addFailed: "添加失败",
    removeFailed: "移除失败",
    loadFailed: "加载失败",
  },
  filter: {
    all: "全部",
    unassigned: "未指派",
  },
  attrs: {
    title: "词表",
    hint: "Workspace 级统一语言:chess 练的 React,bookkeeping 也认。label→skill 只是一行数据,已有等级休眠不删。",
    name: "属性名",
    kindSkill: "skill(分级)",
    kindLabel: "label(不分级)",
    leveled: "分级",
    add: "添加",
    toKind: (target: string) => `→${target}`,
    unleveled: "取消分级",
    delete: "删除",
    createFailed: "创建失败",
    updateFailed: "更新失败",
    deleteFailed: "删除失败",
  },
  shortfall: {
    title: "短板面板",
    hint: "跨项目聚合缺口——我该练什么。",
    empty: "暂无缺口 ✔",
    missing: (n: number) => `缺门 ${n}`,
    delta: (n: number) => `共差 ${n} 级`,
    unrated: (n: number) => `未评级 ${n}`,
  },
  assign: {
    open: "分配",
    reassign: "重新分配",
    none: "未指派",
    assignMe: "指派给我",
    assignMember: "分配成员…",
    assignTo: "指派",
    assignBtn: "指派",
    confirmAnyway: "仍然指派",
    warningPrefix: "该候选存在未满足项——",
  },
  assignDialog: {
    assignMe: "指派给我",
    assignMember: "分配成员…",
    pickMember: "选择成员",
    assignBtn: "指派",
    clear: "取消指派",
    close: "关闭",
    anyway: "仍然指派",
    unmetWarning: "存在未满足项(缺能力/差距/未评级),指派后请关注。",
  },
  gh: {
    patTitle: "GitHub PAT(workspace 级)",
    patHint: "fine-grained token,勾选所需仓库;contents:write + pulls:read。保存后只显示尾 4 位。",
    patInput: "粘贴 PAT",
    patSave: "保存 PAT",
    patConfigured: (hint: string) => `已配置(${hint})`,
    patCleared: "已清除",
    ghUser: "GitHub 用户名",
    ghUserSaved: "保存",
    button: "GitHub",
    panelTitle: "GitHub 集成",
    repos: "挂载仓库",
    repoInput: "owner/name",
    repoAdd: "挂载",
    repoEmpty: "未挂载仓库——建分支/自动流转需先挂载。",
    rules: "事件 → 状态映射(GitHub 永不知道你的列名)",
    ruleBranch: "分支创建",
    rulePrOpen: "PR 打开",
    rulePrMerged: "PR 合并",
    rulePrClosed: "PR 关闭未合并",
    ruleNone: "(不映射)",
    rulesSaved: "映射已保存",
    branch: "创建分支",
    branchTitle: "创建 GitHub 分支",
    branchRepo: "仓库",
    branchBase: "基线分支",
    branchName: "分支名",
    branchCreate: "创建",
    gitRefs: "GitHub 关联",
    gitRefsEmpty: "暂无关联分支/PR。",
    stateOpen: "open",
    stateMerged: "已合并",
    stateClosed: "已关闭",
    stateBranch: "分支",
    statePr: "PR",
    loadFailed: "加载失败",
    saved: "已保存",
  },
  notif: {
    title: "通知",
    empty: "暂无通知",
    markAll: "全部已读",
    advanceTo: (name: string) => `推进到 ${name}`,
    advanceFailed: "推进失败",
    bell: "通知",
    kinds: { status_changed: "状态变更", assigned: "被指派", commented: "评论" } as Record<string, string>,
  },
  time: {
    title: (key: string) => `${key} · 工时`,
    back: "← 看板",
    empty: "还没有工时记录——在 item 详情里开始计时或补录。",
    total: "项目合计",
    byMember: "按人聚合",
    member: "成员",
    minutes: "总时长",
    entries: "条目数",
    section: "工时",
    running: "计时中…",
    start: "开始计时",
    stop: "停止",
    addManual: "补录",
    minutesLabel: "分钟",
    noteLabel: "备注(可选)",
    save: "保存",
    failed: "操作失败",
    fmt: (m: number) => (m >= 60 ? `${Math.floor(m / 60)}h ${m % 60}m` : `${m}m`),
  },
  activity: {
    created: "创建",
    status_changed: "状态变更",
    title_changed: "标题变更",
    description_changed: "描述变更",
    assigned: "指派",
    unassigned: "取消指派",
    requirement_changed: "需求变更",
  },
  verdicts: {
    satisfied: (a: string) => `✓ 满足(${a})`,
    surplus: (a: string) => `✓ 有余(${a})`,
    gap: (a: string, d: number, r: number, act: number) => `△ 差 ${d} 级(${a}:需≥${r},有 ${act})`,
    unrated: (a: string, r: number) => `△ 有但未评级(${a},需≥${r})——差距未知`,
    missing: (a: string) => `✗ 缺能力(${a})`,
  },
  signal: {
    GREEN: "✔ 全满足",
    YELLOW: "△ 有差距",
    RED: "✗ 有缺门",
  },
};
