// 文案外置(中文优先;加英文时改这里)
export const t = {
  appName: "扬州 yangzhou",
  login: {
    title: "登录",
    username: "用户名",
    password: "密码",
    submit: "登录",
    hint: "全新服务器将以首个账号自动初始化",
    failed: "登录失败",
  },
  projects: {
    title: "项目",
    createKey: "KEY(如 CHE)",
    createName: "名称",
    create: "创建项目",
    empty: "还没有项目,建一个",
    enter: "打开看板",
    signalNow: "可行性",
  },
  board: {
    addItem: "新建 item",
    dropHere: "拖到这里",
    moveFailed: "迁移失败",
    detail: "详情",
  },
  item: {
    title: "标题",
    description: "描述",
    status: "状态",
    type: "类型",
    requirements: "需求",
    addRequirement: "加一条需求",
    attribute: "属性",
    minLevel: "最低等级",
    none: "不分级(presence)",
    save: "保存",
    saved: "已保存",
    verdicts: "判定",
    signal: "聚合信号",
    back: "← 返回看板",
  },
  verdicts: {
    satisfied: (a: string) => `✓ 满足(${a})`,
    surplus: (a: string) => `✓ 有余(${a})`,
    gap: (a: string, d: number, r: number, act: number) => `△ 差 ${d} 级(${a}:需≥${r},有 ${act})`,
    unrated: (a: string, r: number) => `△ 有但未评级(${a},需≥${r})——差距未知`,
    missing: (a: string) => `✗ 缺能力(${a})`,
  },
  signal: {
    GREEN: "✔ 全满足",
    YELLOW: "△ 有差距",
    RED: "✗ 有缺门",
  },
};
