-- JCW-154: V12-S1 Sprint 平面(spec docs/spec/0010-v12-itemgroup.md)
-- item_group:项目内分组容器,v1 仅 'sprint'(Phase 3 追加 'release' = 一条 ALTER)
-- item_group_member:item × group 多对多;同一 item 至多属于一个 planned/active sprint(应用层不变量,spec 裁决 2)

create table item_group (
    id          bigint generated by default as identity primary key,
    object_id   uuid          not null,
    project_id  bigint        not null,
    type        varchar(20)   not null default 'sprint',
    name        varchar(100)  not null,
    status      varchar(20)   not null default 'planned',
    start_date  date,
    end_date    date,
    created_at  timestamptz   not null default now(),
    updated_at  timestamptz   not null default now(),

    constraint uk_item_group_object_id unique (object_id),
    constraint fk_item_group_project   foreign key (project_id) references project (id),
    constraint ck_item_group_type      check (type in ('sprint')),
    constraint ck_item_group_status    check (status in ('planned', 'active', 'completed'))
);

create index ix_item_group_project on item_group(project_id);

create table item_group_member (
    id          bigint generated by default as identity primary key,
    object_id   uuid          not null,
    group_id    bigint        not null,
    item_id     bigint        not null,
    created_at  timestamptz   not null default now(),

    constraint uk_item_group_member_object_id unique (object_id),
    constraint uk_item_group_member           unique (group_id, item_id),
    constraint fk_item_group_member_group     foreign key (group_id) references item_group (id),
    constraint fk_item_group_member_item      foreign key (item_id) references item (id)
);

create index ix_item_group_member_item on item_group_member(item_id);
