-- JCW-162: V14 ItemGroup Phase 2 Milestone(spec docs/spec/0011-v14-itemgroup-phase2.md)
-- milestone:项目时间轴目标节点(PRD §9);非 ItemGroup(独立表)
-- §11「Current 通常最多一个」:0..1 in_progress 由部分唯一索引硬约束(服务层预检给友好 409)

create table milestone (
    id          bigint generated by default as identity primary key,
    object_id   uuid          not null,
    project_id  bigint        not null,
    name        varchar(100)  not null,
    status      varchar(20)   not null default 'planned',
    target_date date,
    created_at  timestamptz   not null default now(),
    updated_at  timestamptz   not null default now(),

    constraint uk_milestone_object_id unique (object_id),
    constraint fk_milestone_project   foreign key (project_id) references project (id),
    constraint ck_milestone_status    check (status in ('planned', 'in_progress', 'completed', 'cancelled'))
);

create index ix_milestone_project on milestone(project_id);

create unique index ux_milestone_project_current on milestone(project_id) where status = 'in_progress';
